user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /

app:
    #resource: "@AppBundle/Controller/"
    #type:     annotation

    #resource: "@AppBundle/Resources/config/routing.yml"
    #prefix: /project

    resource: "@AppBundle/Resources/config/routing.yml"
    prefix: /page

new:
 resource: "@NewBundle/Resources/Config/routing.yml"
 prefix: /test