$(document).ready ->
  # PLUGINS
  # get real year

  year = ->
    d = new Date
    n = d.getFullYear()
    n

  # getyear from form

  voiture = (marque) ->
    console.log marque
    mark = $('#modeles').find($(' :not(option[name=' + marque + ']) '))
    console.log mark
    $('#modeles').removeAttr 'disabled'
    $('#modeles').find $('option').removeClass('hidden')
    mark.addClass 'hidden'
    return

  $('#prix').slider()
  $('#km').slider()
  $('#trouve').select2()
  # $(".js-example-basic-multiple").select2();
  $('.js-example-basic-multiple').select2 {}
  # REGEX
  regHexa = /^#[0-9a-zA-Z]{6}$/
  regYear = /^[1|2][0-9a-zA-Z]{3}$/
  $('#couleurhexa').parent().addClass 'hidden'
  $('#modeles').attr 'disabled', 'disabled'
  $('#marque').change ->
    console.log $('#marque').val()
    marque = $('#marque').val()
    console.log marque
    voiture marque
    return
  $('#anneemin').keyup ->
    if !regYear.test($(this).val()) or $(this).val() > $('#anneemax').val() or $(this).val() < 1900
      $(this).parent().addClass 'has-error'
    else
      $(this).parent().removeClass('has-error').addClass 'has-success'
    return
  $('#anneemax').keyup ->
    if !regYear.test($(this).val()) or $('#anneemin').val() > $(this).val() or $(this) > year()
      $(this).parent().addClass 'has-error'
    else
      $(this).parent().removeClass('has-error').addClass 'has-success'
    return
  $('#couleur').click ->
    console.log $('#couleur').val()
    if $('#couleur').val() == 'vide'
      $('#couleur').parent().addClass 'has-error'
    else if $('#couleur').val() == 'autres'
      $('#couleur').parent().removeClass 'has-error'
      $('#couleurhexa').parent().removeClass 'hidden'
    else
      $('#couleurhexa').parent().addClass 'hidden'
    return
  $('#couleurhexa').keyup ->
    if !regHexa.test($(this).val())
      $(this).parent().addClass 'has-error'
    else
      $(this).parent().removeClass('has-error').addClass 'has-success'
    return
  # $("#carburants input[type=checkbox]").click(function(){
  # console.log($(this).val()) 
  # });
  return

# ---
# generated by js2coffee 2.1.0